# repo env:
#   * REPO_NAME
#   * REPO_BASE
#   * REPO_GROUP
#   * REPO_PATH
#   * REPO_GROUP_PATH
#   * REPO_USER (only available for remote repo)
#   * REPO_EMAIL (only available for remote repo)
#   * REPO_URL (only available for remote repo)
#
# remote env (only available for remote repo):
#   * REMOTE_NAME
#   * REMOTE_HOST
#   * REMOTE_PROTOCOL

create:
  - mkdir ${REPO_BASE}

init:
  git:
    branch: ""
    user: "${REPO_USER}"
    email: "${REPO_EMAIL}"
    url: "${REPO_URL}"
  steps:
    - file:
        name: README.md
        content: "# ${REPO_BASE}"
    - run: touch .gitignore
