name: Build Go

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.2

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: Check go format
      run: bash scripts/check-fmt.sh

    - name: Test
      run: go test ./...

    - name: Build
      run: make build
